"""wwm_sim.values — load per-task VALUES from a doc/text and attach to tasks.

Plumbing only (mirrors wwm_sim.deadlines). A task's value is the reward earned for
delivering it ON TIME (before its deadline); a late delivery earns 0. Not
generated by any model — just loaded from a human-editable list.

File / text format — one task per line, tolerant (whitespace/comma/colon, `#`
comments; a header line like "shelf,value" is skipped automatically):
    15  8.0     # shelf 15 is worth 8 if delivered on time
    7,  2
    42: 5.5
"""
from __future__ import annotations

import os
import re


def parse_values(text: str) -> dict[int, float]:
    out: dict[int, float] = {}
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p for p in re.split(r"[,:\s]+", line) if p]
        if len(parts) < 2:
            continue
        try:
            out[int(parts[0])] = float(parts[1])
        except ValueError:
            continue
    return out


def load_values(source: str) -> dict[int, float]:
    """Load values from a file PATH or a raw TEXT string (either works)."""
    if os.path.exists(source):
        with open(source, "r", encoding="utf-8") as f:
            text = f.read()
    else:
        text = source
    return parse_values(text)


def attach_values(env, values: dict[int, float]) -> int:
    """Attach values onto env's shelves by id. Returns how many were attached."""
    attached = 0
    for sh in env.shelfs:
        v = values.get(sh.id)
        sh.value = v
        if v is not None:
            attached += 1
    return attached


def task_value(shelf) -> float:
    """A shelf's value, defaulting to 1.0 when unset."""
    return 1.0 if shelf.value is None else shelf.value
